name: namespace
description: Dart bindings for namespace.so
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  connectrpc: ^1.0.0
  fixnum: ^1.1.1
  protobuf: ^4.1.1

dev_dependencies:
  http: ^1.4.0
  lints: ^5.0.0
  test: ^1.24.0
